water effect
webaverse/heightfield pull request #12
Opened 2022-10-21 02:08 UTC by tcm390

2022-10-22 18:54 UTC, aryasalehi requested changes

2022-10-23 15:54 UTC, tcm390 commented on layers/water-mesh.js
> +  initSetUp() {
[init particle in constructor](https://github.com/webaverse/heightfield/pull/12/commits/7bcd44fb8f419494d931a73f70bf2ea28799e452)

2022-10-24 19:51 UTC, tcm390 commented on layers/water-mesh.js
> +    const baseUrl = import.meta.url.replace(/(\/)[^\/\\]*$/, '$1');
removed
[clean code](https://github.com/webaverse/heightfield/pull/12/commits/6f1bf572f0292647f32680ccaeff8c369e38cef9)

2022-10-24 19:51 UTC, tcm390 commented on meshes/water-package.js
> +      for (let i= 0; i < particleGLBArray.length; i++) {
[bad space](https://github.com/webaverse/heightfield/pull/12/commits/403c50a24caf3619b3e64e721ff8934f58e22d45)

2022-10-24 19:52 UTC, tcm390 commented on meshes/water-package.js
> +      for (let i= 0; i < particleTextureArray.length; i++) {
[bad space](https://github.com/webaverse/heightfield/pull/12/commits/403c50a24caf3619b3e64e721ff8934f58e22d45)

2022-10-24 19:52 UTC, tcm390 commented on water-effect/loadTexture.js
> +import * as THREE from 'three';
[remove loadTexture.js](https://github.com/webaverse/heightfield/pull/12/commits/fd796bed99c467f1c187d09f8fb91cc727f822e6)

2022-10-24 19:52 UTC, tcm390 commented on water-effect/mesh.js
> +const voronoiNoiseTexture = loadTexture(`./assets/textures/voronoiNoise.jpg`);
[separate loading texture and loading glb](https://github.com/webaverse/heightfield/pull/12/commits/1364422f3d9c4c2259878e534b994a92ebb4ca3d)

2022-10-24 20:35 UTC, tcm390 commented on water-effect/particle.js
> +                  : 1.5 * this.currentSpeed + Math.random() * 0.2;
[clean code](https://github.com/webaverse/heightfield/pull/12/commits/45a4d5cae9f1c55308f2634ec8d6dcdcb797d7c7)

2022-10-24 20:35 UTC, tcm390 commented on water-effect/particle.js
> +    if (currentSwimmingHand && this.lastSwimmingHand !== currentSwimmingHand) {
[clean code](https://github.com/webaverse/heightfield/pull/12/commits/45a4d5cae9f1c55308f2634ec8d6dcdcb797d7c7)

2022-10-25 14:55 UTC, aryasalehi requested changes
I added some comments for cleaning this up
But other than that, this PR is huge, please break this into smaller PRs ( like 3 ) so that it's easier to review

2022-10-25 14:55 UTC, aryasalehi commented on water-effect/assets.js
> +    ripple: `${baseUrl}../water-effect/assets/ripple.glb`,
all of the assets should be added to this repo :
https://github.com/webaverse/procgen-assets
just like the terrain assets

2022-10-25 14:55 UTC, aryasalehi commented on water-effect/particle.js
> +      this.divingLowerSplash.info.velocity[i].y = 0.12 + 0.01 * Math.random();
why these values don't have names ?

2022-10-25 14:55 UTC, aryasalehi commented on water-effect/particle.js
> +      brokenAttribute.setX(i, 0.2 + Math.random() * 0.1);
I don't get the random math, these values should be variables with names

2022-10-25 14:55 UTC, aryasalehi commented on water-effect/particle.js
> +          if (this.bubble.info.offset[i] >= 30)
These values should be variables, constants at the top of the file, so that we can change them easily

2022-10-25 15:23 UTC, closed without merging